### ISSUE TITLE
Background in transcripts for weakly supervised action segmentation?

### ISSUE THREAD

**Issue by atalnarayan** [coin-dataset/code#5]
Hi,
For the weakly supervised segmentation task, do you include background in the ordered transcripts?
For e.g., if a video has actions as (a_1, a_2, a_3) in respective order, but has background at the start, and in between a_2 and a_3, would the ordered transcript as per your paper's implementation be (b, a_1, a_2, b, a_3), or just (a_1, a_2, a_3)?
Thanks in advance!

**Comment by yzheng97** [comment]
The transcript should be (b, a_1, a_2, b, a_3). For the details of the annotation, you could refer to the Breakfast dataset: https://uni-bonn.sciebo.de/s/5ZEp7uWAVRQQMnh/download

**Comment by yzheng97** [comment]
In breakfast, the background "step" is denoted as `SIL`.

**Comment by atalnarayan** [comment]
Hi,
Thanks for your response! Yes, I am aware of the annotation in breakfast dataset, but wanted to confirm the inclusion of background in the transcript for experiments reported in the COIN paper since the json file does not have annotations for background regions.
